import FavoriteBorderOutlinedIcon from "@mui/icons-material/FavoriteBorderOutlined";
import VisibilityOutlinedIcon from "@mui/icons-material/VisibilityOutlined";
import StarOutlinedIcon from "@mui/icons-material/StarOutlined";

export const ITEMCARD = [
  {
    id: 1,
    offDiscount: "-40%",
    loveEmoji: <FavoriteBorderOutlinedIcon />,
    eyeEmoji: <VisibilityOutlinedIcon />,
    image: "./g92-2-500x500 1 (1).png",
    itemName: " HAVIT HV-G29 Gamepad",
    itemPrice: "$120",
    itemDiscount: "$160",
    Rate: <StarOutlinedIcon />,
    reviews: "(88)",
  },
  {
    id: 2,
    offDiscount: "-35%",
    loveEmoji: <FavoriteBorderOutlinedIcon />,
    eyeEmoji: <VisibilityOutlinedIcon />,
    image: "./ak-900-01-500x500 1.png",
    itemName: "AK-900 Wired Keyboard",
    itemPrice: "$960",
    itemDiscount: "$1160",
    Rate: <StarOutlinedIcon />,
    reviews: "(75)",
  },
  {
    id: 3,
    offDiscount: "-30%",
    loveEmoji: <FavoriteBorderOutlinedIcon />,
    eyeEmoji: <VisibilityOutlinedIcon />,
    image: "./g27cq4-500x500 1.png",
    itemName: "IPS LCD Gaming Monitor",
    itemPrice: "$370",
    itemDiscount: "$400",
    Rate: <StarOutlinedIcon />,
    reviews: "99",
  },
  {
    id: 4,
    offDiscount: "-25%",
    loveEmoji: <FavoriteBorderOutlinedIcon />,
    eyeEmoji: <VisibilityOutlinedIcon />,
    image: "./sam-moghadam-khamseh-kvmdsTrGOBM-unsplash 1 (1).png",
    itemName: "S-Series Comfort Chair",
    itemPrice: "$375",
    itemDiscount: "$400",
    Rate: <StarOutlinedIcon />,
    reviews: "(99)",
  },
  {
    id: 5,
    offDiscount: "-35%",
    loveEmoji: <FavoriteBorderOutlinedIcon />,
    eyeEmoji: <VisibilityOutlinedIcon />,
    image: "./ak-900-01-500x500 1.png",
    itemName: "AK-900 Wired Keyboard",
    itemPrice: "$960",
    itemDiscount: "$1160",
    Rate: <StarOutlinedIcon />,
    reviews: "(75)",
  },
];
